"""DaVinci Resolve Python script generator.

Generates a Python script that uses the DaVinci Resolve scripting API
to create a new project, import media, and build a timeline from a CutList.

The generated script requires:
- DaVinci Resolve (Studio edition for external scripts, or free via Scripts menu)
- RESOLVE_SCRIPT_API / RESOLVE_SCRIPT_LIB / PYTHONPATH environment variables set
  (see DaVinci Resolve documentation for your platform)

Users run the generated script while DaVinci Resolve is open.
"""

from __future__ import annotations

from pathlib import Path

from snipsnap.models import CutList, CutSegment


def _unique_sources(segments: list[CutSegment]) -> list[str]:
    """Return unique source file paths in order of first appearance."""
    seen: list[str] = []
    for seg in segments:
        if seg.source_file not in seen:
            seen.append(seg.source_file)
    return seen


def generate_davinci_script(cut_list: CutList, frame_rate: int = 24) -> str:
    """Generate a DaVinci Resolve Python automation script from a CutList.

    The generated script connects to a running DaVinci Resolve instance,
    creates a new project, imports all media files, and builds a timeline
    with precise in/out points matching the cut list.

    Args:
        cut_list: The CutList containing ordered CutSegments.
        frame_rate: Frame rate used for converting seconds to frame numbers.
                    Default 24.

    Returns:
        A Python script as a string that can be saved to a .py file and run
        while DaVinci Resolve is open.
    """
    project_name = cut_list.theme or "SnipSnap Cut"
    # Sanitize project name for use as a Python string literal
    safe_project_name = project_name.replace('"', '\\"')

    segments = sorted(cut_list.segments, key=lambda s: s.order)
    unique_sources = _unique_sources(segments)

    lines: list[str] = []

    # --- Header ---
    lines.append('#!/usr/bin/env python')
    lines.append('"""DaVinci Resolve automation script generated by SnipSnap.')
    lines.append('')
    lines.append('Prerequisites:')
    lines.append('  1. DaVinci Resolve must be running.')
    lines.append('  2. Set environment variables (macOS example):')
    lines.append('       export RESOLVE_SCRIPT_API="/Library/Application Support/Blackmagic Design/DaVinci Resolve/Developer/Scripting"')
    lines.append('       export RESOLVE_SCRIPT_LIB="/Applications/DaVinci Resolve/DaVinci Resolve.app/Contents/Libraries/Fusion/fusionscript.so"')
    lines.append('       export PYTHONPATH="$PYTHONPATH:$RESOLVE_SCRIPT_API/Modules/"')
    lines.append('  3. Run this script: python resolve_script.py')
    lines.append('"""')
    lines.append('')

    # --- Imports ---
    lines.append('import sys')
    lines.append('')
    lines.append('try:')
    lines.append('    import DaVinciResolveScript as dvr_script')
    lines.append('except ImportError:')
    lines.append('    print("ERROR: DaVinciResolveScript module not found.")')
    lines.append('    print("Ensure PYTHONPATH includes the Resolve scripting Modules directory.")')
    lines.append('    sys.exit(1)')
    lines.append('')

    # --- Constants ---
    lines.append(f'FRAME_RATE = {frame_rate}')
    lines.append(f'PROJECT_NAME = "{safe_project_name}"')
    lines.append(f'TIMELINE_NAME = "{safe_project_name} - Timeline"')
    lines.append('')

    # --- Media paths ---
    lines.append('# Media files referenced by this cut list')
    lines.append('MEDIA_FILES = [')
    for src in unique_sources:
        safe_src = src.replace('\\', '\\\\').replace('"', '\\"')
        lines.append(f'    "{safe_src}",')
    lines.append(']')
    lines.append('')

    # --- Clip definitions ---
    lines.append('# Clip placements: (media_index, start_frame, end_frame, description)')
    lines.append('# media_index refers to the MEDIA_FILES list above (0-based)')
    lines.append('# start_frame and end_frame are inclusive source in/out points')
    lines.append('CLIPS = [')
    for seg in segments:
        src_idx = unique_sources.index(seg.source_file)
        start_frame = round(seg.start * frame_rate)
        end_frame = round(seg.end * frame_rate)
        safe_desc = seg.description.replace('"', '\\"') if seg.description else ""
        lines.append(f'    # {safe_desc}')
        lines.append(
            f'    {{"media_index": {src_idx}, '
            f'"start_frame": {start_frame}, '
            f'"end_frame": {end_frame}}},  '
            f'# {Path(seg.source_file).name} [{seg.start:.3f}s–{seg.end:.3f}s]'
        )
    lines.append(']')
    lines.append('')

    # --- Main script body ---
    lines.append('')
    lines.append('def main() -> None:')
    lines.append('    # 1. Connect to DaVinci Resolve')
    lines.append('    resolve = dvr_script.scriptapp("Resolve")')
    lines.append('    if resolve is None:')
    lines.append('        print("ERROR: Could not connect to DaVinci Resolve.")')
    lines.append('        print("Make sure DaVinci Resolve is running.")')
    lines.append('        sys.exit(1)')
    lines.append('')
    lines.append('    project_manager = resolve.GetProjectManager()')
    lines.append('')
    lines.append('    # 2. Create a new project')
    lines.append('    project = project_manager.CreateProject(PROJECT_NAME)')
    lines.append('    if project is None:')
    lines.append('        print(f"ERROR: Could not create project \'{PROJECT_NAME}\'.")')
    lines.append('        print("A project with this name may already exist.")')
    lines.append('        sys.exit(1)')
    lines.append('    print(f"Created project: {PROJECT_NAME}")')
    lines.append('')
    lines.append('    # 3. Set timeline frame rate')
    lines.append('    project.SetSetting("timelineFrameRate", str(FRAME_RATE))')
    lines.append('    print(f"Set frame rate: {FRAME_RATE} fps")')
    lines.append('')
    lines.append('    # 4. Import media files into the media pool')
    lines.append('    media_pool = project.GetMediaPool()')
    lines.append('    print(f"Importing {len(MEDIA_FILES)} media file(s)...")')
    lines.append('    media_items = media_pool.ImportMedia(MEDIA_FILES)')
    lines.append('    if not media_items or len(media_items) != len(MEDIA_FILES):')
    lines.append('        imported_count = len(media_items) if media_items else 0')
    lines.append('        print(f"WARNING: Expected {len(MEDIA_FILES)} items, got {imported_count}.")')
    lines.append('        print("Check that all media files exist and are readable.")')
    lines.append('        if not media_items:')
    lines.append('            sys.exit(1)')
    lines.append('')
    lines.append('    for i, path in enumerate(MEDIA_FILES):')
    lines.append('        print(f"  Imported: {path}")')
    lines.append('')
    lines.append('    # 5. Build clip info list with in/out frame values')
    lines.append('    clip_infos = []')
    lines.append('    for clip_def in CLIPS:')
    lines.append('        media_item = media_items[clip_def["media_index"]]')
    lines.append('        clip_infos.append({')
    lines.append('            "mediaPoolItem": media_item,')
    lines.append('            "startFrame": clip_def["start_frame"],')
    lines.append('            "endFrame": clip_def["end_frame"],')
    lines.append('        })')
    lines.append('')
    lines.append('    # 6. Create timeline from clips with precise in/out points')
    lines.append('    print(f"Creating timeline: {TIMELINE_NAME}")')
    lines.append('    if clip_infos:')
    lines.append('        timeline = media_pool.CreateTimelineFromClips(TIMELINE_NAME, clip_infos)')
    lines.append('    else:')
    lines.append('        # Empty cut list: create an empty timeline')
    lines.append('        timeline = media_pool.CreateEmptyTimeline(TIMELINE_NAME)')
    lines.append('')
    lines.append('    if timeline is None:')
    lines.append('        print("ERROR: Failed to create timeline.")')
    lines.append('        sys.exit(1)')
    lines.append('    print(f"Timeline created: {TIMELINE_NAME}")')
    lines.append('    print(f"Clips placed: {len(clip_infos)}")')
    lines.append('')
    lines.append('    # 7. Save the project')
    lines.append('    project_manager.SaveProject()')
    lines.append('    print("Project saved successfully.")')
    lines.append('')
    lines.append('')
    lines.append('if __name__ == "__main__":')
    lines.append('    main()')
    lines.append('')

    return "\n".join(lines)
