"""Interactive setup wizard for SnipSnap.

Guides users through initial configuration:
- OpenRouter API key validation
- Model selection
- Data directory setup
- .env file creation
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Optional

import click

# Model choices with descriptions (model_id, display_name)
MODEL_CHOICES: list[tuple[str, str]] = [
    ("google/gemini-2.5-flash-lite", "Gemini 2.5 Flash Lite (default, fast & cheap)"),
    ("anthropic/claude-3-haiku", "Claude 3 Haiku (fast)"),
    ("openai/gpt-4o-mini", "GPT-4o Mini (balanced)"),
    ("meta-llama/llama-3-8b-instruct", "Llama 3 8B (open source)"),
]


def validate_api_key(api_key: str) -> tuple[bool, str]:
    """Validate an OpenRouter API key by making a lightweight API call.

    Returns (is_valid, error_message_or_empty).
    """
    if not api_key or not api_key.strip():
        return False, "API key cannot be empty"

    try:
        import openai

        client = openai.OpenAI(
            api_key=api_key.strip(),
            base_url="https://openrouter.ai/api/v1",
        )
        # Lightweight call to validate the key
        client.models.list()
        return True, ""
    except openai.AuthenticationError:
        return False, "Invalid API key"
    except openai.APIConnectionError:
        return False, "Cannot connect to OpenRouter (check your internet)"
    except Exception as exc:  # noqa: BLE001
        return False, f"Validation failed: {exc}"


def prompt_for_api_key() -> str:
    """Interactive prompt with validation."""
    click.echo()
    click.echo(click.style("OpenRouter API Key", bold=True))
    click.echo("-" * 20)
    click.echo("Get your API key from: https://openrouter.ai/keys")
    click.echo()

    while True:
        api_key = click.prompt("Enter your OpenRouter API key", hide_input=True)

        click.echo("Validating key...", nl=False)
        is_valid, error = validate_api_key(api_key)

        if is_valid:
            click.echo(click.style(" OK", fg="green"))
            return api_key.strip()
        else:
            click.echo(click.style(f" FAILED ({error})", fg="red"))
            if not click.confirm("Try again?", default=True):
                raise click.Abort()


def prompt_for_model() -> str:
    """Show numbered list, let user select or accept default."""
    click.echo()
    click.echo(click.style("Model Selection", bold=True))
    click.echo("-" * 16)
    click.echo("Choose your default LLM model for curation:")
    click.echo()

    for i, (model_id, description) in enumerate(MODEL_CHOICES, start=1):
        click.echo(f"  [{i}] {description}")
    click.echo(f"  [{len(MODEL_CHOICES) + 1}] Enter custom model ID")
    click.echo()

    default_choice = 1
    while True:
        choice_str = click.prompt(
            f"Select [1-{len(MODEL_CHOICES) + 1}] or press Enter for default",
            default=str(default_choice),
            show_default=False,
        )

        try:
            choice = int(choice_str)
        except ValueError:
            click.echo("Please enter a number.")
            continue

        if 1 <= choice <= len(MODEL_CHOICES):
            model_id, _ = MODEL_CHOICES[choice - 1]
            return model_id
        elif choice == len(MODEL_CHOICES) + 1:
            return click.prompt("Enter custom model ID")
        else:
            click.echo(f"Please enter a number between 1 and {len(MODEL_CHOICES) + 1}.")


def prompt_for_data_dir() -> Path:
    """Prompt for data directory with default."""
    click.echo()
    click.echo(click.style("Data Directory", bold=True))
    click.echo("-" * 14)
    click.echo("Where should SnipSnap store transcriptions and cut lists?")

    default_dir = "./snipsnap_data/"
    dir_str = click.prompt(
        "Press Enter to accept default or enter a path",
        default=default_dir,
        show_default=True,
    )
    return Path(dir_str)


def create_env_file(
    api_key: str,
    model: str,
    data_dir: Path,
    env_path: Optional[Path] = None,
) -> Path:
    """Write .env file, return path. Backs up existing .env if present."""
    if env_path is None:
        env_path = Path(".env")

    # Backup existing .env if present
    if env_path.exists():
        backup_path = env_path.with_suffix(".env.backup")
        shutil.copy(env_path, backup_path)
        click.echo(f"Backed up existing .env to {backup_path}")

    content = f"""\
# SnipSnap Configuration
# Generated by `snipsnap init`

# OpenRouter API key (required for curation)
OPENROUTER_API_KEY={api_key}

# LLM model for curation
SNIPSNAP_MODEL={model}

# Data directory for transcriptions and cut lists
SNIPSNAP_DATA_DIR={data_dir}

# Whisper model size (tiny, base, small, medium, large-v2, large-v3)
# SNIPSNAP_WHISPER_MODEL=small
"""
    env_path.write_text(content)
    return env_path


def ensure_data_directory(data_dir: Path) -> None:
    """Create data directory structure if needed."""
    data_dir.mkdir(parents=True, exist_ok=True)
    (data_dir / "transcriptions").mkdir(exist_ok=True)
    (data_dir / "cutlists").mkdir(exist_ok=True)
    (data_dir / "exports").mkdir(exist_ok=True)


def show_whats_next() -> None:
    """Print next steps after successful initialization."""
    click.echo()
    click.echo(click.style("What's Next", bold=True))
    click.echo("-" * 11)
    click.echo()
    click.echo("1. Transcribe videos:")
    click.echo("   snipsnap transcribe ./your-footage-folder")
    click.echo()
    click.echo("2. Curate with a prompt:")
    click.echo('   snipsnap curate --prompt "find the best moments"')
    click.echo()
    click.echo("3. Export to your NLE:")
    click.echo("   snipsnap export --format edl <cut-list-id>")
    click.echo()
    click.echo("Run 'snipsnap status' to see your pipeline state.")
    click.echo("Run 'snipsnap --help' for all commands.")


def run_wizard(
    api_key: Optional[str] = None,
    model: Optional[str] = None,
    data_dir: Optional[Path] = None,
    non_interactive: bool = False,
) -> None:
    """Run the full setup wizard.

    Args:
        api_key: Pre-provided API key (skips prompt if valid)
        model: Pre-provided model (skips prompt)
        data_dir: Pre-provided data directory (skips prompt)
        non_interactive: If True, use defaults without prompting
    """
    click.echo()
    click.echo(click.style("Welcome to SnipSnap!", bold=True, fg="cyan"))
    click.echo("=" * 20)
    click.echo()
    click.echo("This wizard will help you set up your configuration.")

    # API key
    if api_key:
        click.echo()
        click.echo("Validating provided API key...", nl=False)
        is_valid, error = validate_api_key(api_key)
        if not is_valid:
            click.echo(click.style(f" FAILED ({error})", fg="red"))
            raise click.ClickException(f"Invalid API key: {error}")
        click.echo(click.style(" OK", fg="green"))
        final_api_key = api_key.strip()
    elif non_interactive:
        raise click.ClickException("--api-key is required in non-interactive mode")
    else:
        final_api_key = prompt_for_api_key()

    # Model
    if model:
        final_model = model
    elif non_interactive:
        final_model = MODEL_CHOICES[0][0]  # Default to first option
    else:
        final_model = prompt_for_model()

    # Data directory
    if data_dir:
        final_data_dir = data_dir
    elif non_interactive:
        final_data_dir = Path("./snipsnap_data/")
    else:
        final_data_dir = prompt_for_data_dir()

    # Create files
    click.echo()
    click.echo(click.style("Configuration", bold=True))
    click.echo("-" * 13)

    click.echo("Creating .env file...", nl=False)
    env_path = create_env_file(final_api_key, final_model, final_data_dir)
    click.echo(click.style(" done", fg="green"))

    click.echo("Creating data directory...", nl=False)
    ensure_data_directory(final_data_dir)
    click.echo(click.style(" done", fg="green"))

    click.echo()
    click.echo(click.style("Setup complete!", fg="green", bold=True))
    click.echo(f"  .env file: {env_path.absolute()}")
    click.echo(f"  Data dir:  {final_data_dir.absolute()}")

    show_whats_next()
